import type { Metadata } from "next";
import { UserProvider } from '@auth0/nextjs-auth0/client';
// import localFont from "next/font/local";
import { GeistSans } from "geist/font/sans";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/mbx5ori.css" />
      </head>
      <UserProvider>
        <body
          className={`${GeistSans.className} antialiased`}
        >
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
