import type { Metadata } from "next";
import { UserProvider } from '@auth0/nextjs-auth0/client';
// import localFont from "next/font/local";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import clsx from "clsx";
import { getDeviceType } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isMobile } = getDeviceType();
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/mbx5ori.css" />
      </head>
      <UserProvider>
        <body
          className={clsx(`${GeistSans.className} antialiased`, isMobile && 'app-mobile',)}
        >
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
